### ISSUE TITLE
About the TODO in your PRINT_END

### ISSUE THREAD

**Issue by ghost** [garethky/klipper-voron2.4-config#1]
You are talkin about a TODO in your PRINT_END.
Perhaps we can send a height in the slicer end_gcode like;
I'm using SuperSlicer but it should also work with PrusaSlicer

PRINT_END OBJECT_HEIGHT={z_offset+min(layer_z+10, max_print_height)}

And do something with it in PRINT_END macro

**Comment by garethky** [comment]
What I meant was, if you print a tall object and your printer's max z value is maybe 250... lets say your tall object is up at 245... then if the macro tries to raise the Z height by 10mm it will error out and the toolhead will be stuck where it is, possibly melting the print you just spend hours or days on.

So the right thing it to raise Z by at most 10mm, but by less if there is less room available in the print volume. so to fix this I implemented SAFE_LIFT_Z that does this: https://github.com/garethky/klipper-voron2.4-config/commit/bdfb156a0a7e1db95125e9b08a499b5250f9030a#diff-d49809beb515fe093c0346f2378e86e7359ad1bceaf2ee39aa7d68f6189dc627R653
